name: Client checks

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm --prefix ./client install

    - name: Build project
      run: npm --prefix ./client run build

    - name: Run tests
      run: npm --prefix ./client test
